project_id = "luohiaujigqcjpzicxiz"

[functions.ai-chat-router]
verify_jwt = false

[functions.test-chat]
verify_jwt = false

[functions.generate-pick]
verify_jwt = false

[functions.fetch-odds]
verify_jwt = true

[functions.fetch-standings]
verify_jwt = true

[functions.seed-nfl-schedule]
verify_jwt = false

[functions.generate-nfl-picks-cron]
verify_jwt = false

[functions.fetch-nfl-stats]
verify_jwt = false

[functions.update-nfl-team-stats]
verify_jwt = false

[functions.web-search]
verify_jwt = true
